name: Deploy Felsverzeichnis

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to production
        run: |
          cd /home/vorstieg/felsverzeichnis_prod
          git pull origin main
          npm install
          npm run build
          PM2_HOME=/home/vorstieg/.pm2 pm2 restart felsverzeichnis_prod
